spring.application.name=prince
spring.datasource.url=jdbc:mysql://localhost:3306/prince_db
spring.datasource.username=root
spring.datasource.password=H@rish
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

